<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.18.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microservicios.Atracciones.Identify.DataAccess\Microservicios.Atracciones.Identify.DataAccess.csproj" />
    <ProjectReference Include="..\Microservicios.Atracciones.Identify.DataManagement\Microservicios.Atracciones.Identify.DataManagement.csproj" />
  </ItemGroup>
</Project>
