<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.1.0" />
    <PackageReference Include="QuestPDF" Version="2026.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microservicios.Atracciones.Booking.DataManagement\Microservicios.Atracciones.Booking.DataManagement.csproj" />
  </ItemGroup>

</Project>
